apiVersion: v1
kind: Service
metadata:
  labels:
    app: productsqlserver
  name: foursixproductsql
spec:
  selector:
    app: productmssql
  ports:
  - port: 1433
    protocol: TCP
    targetPort: 1433
  type: LoadBalancer
