apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-product
  name: redis-product
spec:
  selector:
    app: redis-product
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  type: LoadBalancer
